export enum Model {
    RECTANGLE = "RECTANGLE",
    RECTANGLE_BORDER = "RECTANGLE_BORDER",
    POINT = "POINT",
    POINTS = "POINTS",
    POINTS_BORDER = "POINTS_BORDER",
    TRIANGLE_BORDER = "TRIANGLE_BORDER",
    LINE = "LINE",
    TEXT = "TEXT",
    CIRCLE = "CIRCLE",
    CIRCLE_BORDER = "CIRCLE_BORDER",
    ARC = "ARC",
}